# Preface {.unnumbered}

You may wonder, another book about Quantum Computing? More documentation? We already have:

* [Qiskit documentation](https://docs.quantum.ibm.com/guides/hello-world)
* DWave's documentation around [optimization](https://docs.dwavequantum.com/en/latest/index.html)
* Pennylane for [QML and simulation](https://pennylane.ai/qml) and [codebooks](https://pennylane.ai/codebook/learning-paths)
* Books that also cover the theoretical part in depth like [this one](https://kawaihome.link/jbooks/qcomp-short/cover.html)
* Even some relevant works that go in detail on this, books and stuff [@dewolf2023quantumcomputinglecturenotes; @watrous2025understandingquantuminformationcomputation; @nielsen2010quantum; @yanofsky2008quantum]

Well, by telling it from a different perspective it may help people coming from different fields (meaning, non-physicists) grasp the idea behind quantum computing. This is also a work for myself, as it will definitely help me better understand some of the concepts. Just by explaining things I found it is the best way to challenge ones knowledge about a field you are trying to master.

Also, it costs nothing so, no harm done. Code snippets are easier to maintain so hopefully, everything will work with the latest versions. I hope you enjoy reading it as much as I have learned creating it.

## About me

My name is Iraitz Montalbán. I have a background in Computer Science, and I first encountered quantum computing by chance during an internship in 2010. At the time, a group of researchers was working on something called quantum computing, which, back then, was largely a mathematical framework rather than a practical technology.

That experience sparked my interest in the field, and I continued to follow its evolution. Eventually, I pursued a Master's degree in Quantum Computing Technologies at UPM and went on to work with several startups developing quantum computing technologies.

Feel free to keep in touch at [iraitz.info](https://iraitz.info/).
